/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.107
 * Generated at: 2021-03-16 03:19:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class intro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- menu -->\r\n");
      out.write("<nav class=\"navbar navbar-default  navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("      비트교육센터\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("    \t<li><a href=\"index.do\">home</a></li>\r\n");
      out.write("    \t<li><a href=\"intro.do\">intro</a></li>\r\n");
      out.write("    \t<li><a href=\"list.do\">dept</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- content -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t  <div class=\"col-xs-12\">\r\n");
      out.write("\t  <!-- start -->\r\n");
      out.write("\t  <ol class=\"breadcrumb\">\r\n");
      out.write("  <li><a href=\"index.do\">Home</a></li>\r\n");
      out.write("  <li class=\"active\">intro</li>\r\n");
      out.write("</ol>\r\n");
      out.write("\t  <div class=\"page-header\">\r\n");
      out.write("  <h1>내장 앱 <small>소개</small></h1>\r\n");
      out.write("</div>\r\n");
      out.write("\t  <h3>내장 앱</h3>\r\n");
      out.write("\t  <h5>모든 Mac에는 창의성과 생산성을 위한 강력한 도구들이 함께합니다. 바로 당신이 더 효율적으로 궁금한 것을 찾아보고, 다른 사람들과 소통하고, 업무를 볼 수 있게 해주는 앱들이죠.</h5>\r\n");
      out.write("\t  <p>웹을 더욱 즐길 수 있게 해주는 혁신적 기능을 갖춘 Safari. 이제 보다 다양한 측면에서 그 즐거움을 뒷받침해줍니다. 웹서핑 중에도 당신의 정보와 Mac을 안전하게 보호해주는 내장 개인 정보 보호 기능, 당신이 즐겨 찾는 웹사이트를 쉽고 빠르게 저장하고, 찾고, 공유할 수 있도록 업데이트된 시작 페이지, 게다가 Siri 제안 기능이 책갈피, 읽기 목록의 링크, ‘iCloud 탭’, 메시지 앱에서 받은 링크 등을 표시해 더 나은 웹 경험을 구현하죠.</p>\r\n");
      out.write("\t  <!-- end -->\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t  <div class=\"col-xs-12 text-center\">\r\n");
      out.write("\t  Copyright &copy; 비트캠프 </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
